title: Fangyu HOU
first_name: Fangyu
last_name: HOU

contact_note: >
  Feel free to contact me via email houfy@mail.tsinghua.edu.cn/ houfy761@gmail.com.

description: >
  Personal academic website of Fangyu HOU.

keywords: Physics, AI4Science, Biophysics & Soft Matter

url: https://houfy761-tech.github.io
baseurl:

